### ISSUE TITLE
jcuda 10 

### ISSUE THREAD

**Issue by jf17** [jcuda/jcuda-samples#3]
Windows 10

 jcuda-samples/JCudaSamples/src/main/java/jcuda/runtime/samples/JCudaPrintDeviceInfo.java

Exception in thread "main" jcuda.CudaException: cudaErrorInsufficientDriver
	at jcuda.runtime.JCuda.checkResult(JCuda.java:481)
	at jcuda.runtime.JCuda.cudaGetDeviceCount(JCuda.java:527)
	at demo.JCudaPrintDeviceInfo.main(JCudaPrintDeviceInfo.java:14)

**Comment by jcuda** [comment]
Can you provide more information about your CUDA version and driver version? 

Do any of the official NVIDIA CUDA samples work for you?

**Comment by jf17** [comment]
> 
> 
> Can you provide more information about your CUDA version and driver version?
> 
> Do any of the official NVIDIA CUDA samples work for you?

official NVIDIA CUDA samples work !
NVIDIA CUDA 10.0

- jcuda-10.0.0.jar 
- jcublas-10.0.0.jar 
- jcufft-10.0.0.jar 
- jcusparse-10.0.0.jar 
- jcusolver-10.0.0.jar 
- jcurand-10.0.0.jar 
- jnvgraph-10.0.0.jar 
- jcudnn-10.0.0.jar 
- commons-math3-3.6.1.jar

**Comment by jcuda** [comment]
Without further information, I can hardly do more than a websearch for `cudaErrorInsufficientDriver` and guess about the possible reasons (a relatively recent thread is https://devtalk.nvidia.com/default/topic/1045583/b/t/post/5305456/ , but there certainly are *many* possible reasons).

The fact that the CUDA samples work is a bit strange. Can you post the output of running the `CUDA Samples\v10.0\1_Utilities\deviceQuery` sample? (It should contain all relevant version information)

**Comment by jf17** [comment]
Ok. Thank you .

**Comment by jcuda** [comment]
I'd really like to help you sorting this out (particularly, because I don't have Windows 10, and others might run into the same problem). But in order to figure out what the *reason* for this problem is, you probably have to provide more information.
