### ISSUE TITLE
JCuda samples for windows 64 pom.xml should reference jcuda-windows64 project

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda-samples#6]
I had to add dependency jcuda-windows64 ver 6.5 to build jcuda-samples project

**Comment by jcuda** [comment]
Version 6.5 was not even in Maven Central yet, and it should not be necessary to add dependencies for specific operating systems. The issue is already discussed at https://github.com/jcuda/jcuda-parent/issues/1 , so I'm closing this one here.
